version: '3'

services:
  db:
    hostname: mongodb
    image: mongo:4.2-bionic
    command: mongod --port 27017
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env.db

  zookeeper:
    image: wurstmeister/zookeeper

  kafka-service:
    image: wurstmeister/kafka
    restart: always
    env_file:
      - .env.kafka
    ports:
    - 29092:29092
    - 9092:9092
    depends_on:
      - zookeeper